dist: trusty

language: node_js

node_js:
  - '7.4.0'

matrix:
  fast_finish: true

cache:
  directories:
    - sysconfcpus

install:
   - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - npm install -g elm
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-package install -y

script:
  - sh ./util/publish.sh
